export default {
  logo: require('../../assets/Image/logokalyan.jpeg'),
  back: require('../../assets/Icon/back.png'),
  ic_chat: require('../../assets/Icon/chat.png'),
  ic_chat_bold: require('../../assets/Icon/chat_bold.png'),
  ic_map: require('../../assets/Icon/map.png'),
  ic_map_bold: require('../../assets/Icon/map_bold.png'),
  ic_storage: require('../../assets/Icon/storage.png'),
  ic_storage_bold: require('../../assets/Icon/storage_bold.png'),
  ic_map_bold: require('../../assets/Icon/map_bold.png'),
  ic_camera: require('../../assets/Icon/camera.png'),
  ic_camera_bold: require('../../assets/Icon/camera_bold.png'),
  ic_profile: require('../../assets/Icon/user.png'),
  ic_search: require('../../assets/Icon/search.png'),
  ic_comment: require('../../assets/Icon/comment.png'),
};
