export const SET_MAIN_ROUTE = 'SET_MAIN_ROUTE';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
